# ==========================
# Stage 1 - Build
# ==========================
FROM eclipse-temurin:17-jdk AS builder

WORKDIR /app

COPY Hello.java .

RUN javac Hello.java

# ==========================
# Stage 2 - Runtime
# ==========================
FROM eclipse-temurin:17-jre

WORKDIR /app

COPY --from=builder /app/Hello.class .

CMD ["java", "Hello"]
